- name: Install EPEL
  package:
    name: epel-release
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution=="RedHat"

- name: Install EPEL (Amazon Linux 2) - check
  stat: path=/etc/yum.repos.d/epel.repo
  register: epel_repo
  when: ansible_distribution == "Amazon" and ansible_service_mgr == 'systemd'

- name: Install EPEL (Amazon Linux 2) - install
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present
  when: ansible_distribution == "Amazon" and ansible_service_mgr == 'systemd' and not epel_repo.stat.exists

- name: Install EPEL (Amazon Linux 2) - import GPG key
  rpm_key:
    key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
    state: present
  when: ansible_distribution == "Amazon" and ansible_service_mgr == 'systemd' and not epel_repo.stat.exists

- name: Install python2-dnf for Fedora dnf support
  raw: dnf install -y python2-dnf
  when:
    - ansible_distribution == "Fedora"
    - ansible_python.version.major == 2
  register: fedora_dnf
  changed_when: '"Nothing to do." not in fedora_dnf.stdout'

- name: Install openvpn
  package:
   name: "{{ item }}"
   state: present
  with_items:
    - openvpn
    - openssl

- name: Install LDAP plugin
  package:
   name: openvpn-auth-ldap
   state: present
  when: openvpn_use_ldap

- name: Install mfa DUO plugin
  include: mfa_duo.yml
  when: openvpn_use_mfa_duo

# RHEL has the group 'nobody', 'Debian/Ubuntu' have 'nogroup'
# standardize on 'nogroup'
- name: Ensure group 'nogroup' is present
  group:
    name: nogroup
    state: present
    system: yes
