- stat: path=/opt/duo/duo_openvpn.so
  become: true
  register: duo_openvpn_so

- name: download duo_openvpn-{{ mfa_duo_version }}
  become: true
  unarchive:
    src: https://github.com/duosecurity/duo_openvpn/archive/{{mfa_duo_version}}.tar.gz
    dest: /usr/src
    remote_src: yes
  when: not duo_openvpn_so.stat.exists

- name: install duo_openvpn-{{mfa_duo_version}}
  become: true
  shell: 'cd /usr/src/duo_openvpn-{{mfa_duo_version}}; make & make install'
  when: not duo_openvpn_so.stat.exists
